'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { doc, serverTimestamp, setDoc } from 'firebase/firestore';
import { nanoid } from 'nanoid';
import { db } from '@/lib/firebase';
import { templates } from '@/lib/templates';
import CloudinaryUpload from '@/components/CloudinaryUpload';

const vibes = ['soft', 'romantic', 'playful', 'cinematic', 'deep'];
const fields = {
  sorry: [['promise_1','A promise you will keep'],['promise_2','Another promise'],['promise_3','One more promise']],
  birthday: [['sender_name','Your name'],['balloon_word_1','Balloon word 1'],['balloon_word_2','Balloon word 2'],['balloon_word_3','Balloon word 3'],['balloon_word_4','Balloon word 4'],['age_milestone','Age or milestone']],
  anniversary: [['special_date','Your special date'],['promise_1','Promise 1'],['promise_2','Promise 2'],['promise_3','Promise 3'],['promise_4','Promise 4'],['promise_5','Promise 5']],
  'mothers-day': [['mom_title','What you call them'],['relation','Your relationship'],['secret_note','One thing you never say enough'],['sticky_note_1','Memory 1'],['sticky_note_2','Memory 2'],['sticky_note_3','Memory 3']],
  proposal: [['date_idea','Your dream date idea']],
  friendship: [['sender_name','Your name'],['years_known','Years known'],['one_liner','A line about your bond'],['bond_traits','Traits, separated by commas']],
  puzzle: [['hidden_message','The hidden message']],
  'wedding-invitation': [['bride_name','Bride name'],['groom_name','Groom name'],['wedding_date','Wedding date'],['venue','Venue'],['venue_map_url','Venue map URL'],['event_1_name','First event'],['event_1_time','First event time'],['event_2_name','Second event'],['event_2_time','Second event time'],['event_3_name','Third event'],['event_3_time','Third event time']],
  'surprise-reveal-box': [['hint_1','First hint'],['hint_2','Second hint'],['hint_3','Third hint'],['final_surprise','Final surprise']],
  'a-rose-for-someone-special': [['dedication_line','Your dedication']],
  rakshabandhan: [['rakhi_promise_1','Promise 1'],['rakhi_promise_2','Promise 2'],['rakhi_promise_3','Promise 3'],['unboxing_letter','A final letter']],
};

function normalizeTemplate(id) { return ({ apology: 'sorry', 'birthday-surprise': 'birthday', 'love-letter': 'anniversary', 'letter-for-mom': 'mothers-day', 'be-my-valentine': 'proposal' })[id] || id; }

export default function LegacyCreator({ templateId }) {
  const router = useRouter();
  const template = templates.find((item) => item.id === templateId) || templates.find((item) => item.id === 'sorry');
  const fieldList = fields[normalizeTemplate(template.id)] || [];
  const [step, setStep] = useState(1); const [recipient, setRecipient] = useState(''); const [message, setMessage] = useState(''); const [details, setDetails] = useState({}); const [images, setImages] = useState([]); const [vibe, setVibe] = useState('soft'); const [aiContext, setAiContext] = useState(''); const [busy, setBusy] = useState(false); const [aiBusy, setAiBusy] = useState(false); const [error, setError] = useState('');
  const update = (key, value) => setDetails((current) => ({ ...current, [key]: value }));
  const fill = async () => { setAiBusy(true); setError(''); try { const res = await fetch('/api/ai-message', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ templateId: template.id, recipientName: recipient, tone: vibe === 'deep' ? 'sincere' : vibe, keywords: aiContext, mode: 'fill_template' }) }); const raw = await res.text(); let data; try { data = JSON.parse(raw); } catch { throw new Error(`AI service returned an invalid response (${res.status}). Please try again.`); } if (!res.ok) throw new Error(data.error || 'AI could not fill this template.'); setDetails((current) => ({ ...current, ...(data.details || {}) })); if (!message && data.message) setMessage(data.message); } catch (e) { setError(e.message || 'AI could not fill this template.'); } finally { setAiBusy(false); } };
  const advance = () => { setError(''); if (step === 1 && !recipient.trim()) return setError('Add their name to continue.'); if (step === 3 && !message.trim()) return setError('Write your message before continuing.'); setStep((current) => current + 1); };
  const save = async () => { setBusy(true); setError(''); try { let deviceId = localStorage.getItem('note_device_id'); if (!deviceId) { deviceId = nanoid(32); localStorage.setItem('note_device_id', deviceId); } const id = nanoid(32); await setDoc(doc(db, 'notes', id), { creator_uid: deviceId, recipient_name: recipient.trim(), custom_message: message.trim(), image_urls: images, shagun_qr_url: null, custom_details: { ...details, vibe }, is_paid: false, template: template.id, custom_slug: null, created_at: serverTimestamp(), expires_at: null }); const ids = JSON.parse(localStorage.getItem('created_note_ids') || '[]'); localStorage.setItem('created_note_ids', JSON.stringify([...ids, id])); router.push(`/preview?id=${id}`); } catch (e) { setError(e.message || 'Could not create this experience.'); setBusy(false); } };
  return <main className="shell emotional-creator-shell"><div className="emotional-creator-wrap"><div className="emotional-creator-heading"><span>CLASSIC EXPERIENCE</span><h1>{template.icon} {template.title}</h1><p>Make the classic experience personal, then preview it before payment.</p></div><section className="glass-card emotional-creator-card"><div className="emotional-stepper">{[1,2,3,4].map((item) => <span key={item} className={step >= item ? 'is-active' : ''}>{item}</span>)}</div>
    {step === 1 && <><h2>Who is this for?</h2><div className="form-group"><label className="form-label">Their name</label><input className="form-input" value={recipient} onChange={(e) => setRecipient(e.target.value)} placeholder="Maya, Mom, Bestie…" maxLength={80} /></div></>}
    {step === 2 && <><div className="ai-fill-card"><strong>✨ Fill this template with AI</strong><p>Give a few real details and AI will draft the available fields. You can edit everything.</p><textarea className="form-input" rows="3" value={aiContext} onChange={(e) => setAiContext(e.target.value)} placeholder="e.g. we met in college, she loves chai, 5 years of friendship…" /><button type="button" className="btn-secondary" disabled={aiBusy} onClick={fill}>{aiBusy ? 'Writing your experience…' : '✨ Fill template fields'}</button></div>{fieldList.length ? <div className="legacy-field-grid">{fieldList.map(([key,label]) => <div className="form-group" key={key}><label className="form-label">{label}</label><input className="form-input" type={key.includes('date') ? 'date' : 'text'} value={details[key] || ''} onChange={(e) => update(key, e.target.value)} maxLength={300} /></div>)}</div> : <p className="text-muted">This experience is ready for your personal message in the next step.</p>}</>}
    {step === 3 && <><div className="form-group"><label className="form-label">What do you want to say?</label><textarea className="form-input" rows="6" value={message} onChange={(e) => setMessage(e.target.value)} maxLength={1500} placeholder="Write from the heart…" /></div><div className="form-group"><label className="form-label">Choose your vibe</label><div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>{vibes.map((item) => <button type="button" key={item} onClick={() => setVibe(item)} className={vibe === item ? 'legacy-vibe is-active' : 'legacy-vibe'}>{item}</button>)}</div></div><div className="form-group"><label className="form-label">Photos (optional, up to {template.photoRequirement?.max || 6})</label><CloudinaryUpload onUpload={(url) => setImages((current) => current.length < (template.photoRequirement?.max || 6) ? [...current, url] : current)} /><div className="thumbs">{images.map((url, index) => <button type="button" key={url} onClick={() => setImages(images.filter((_, item) => item !== index))}><img src={url} alt="Selected memory" /></button>)}</div></div></>}
    {step === 4 && <><h2>Ready for your private preview</h2><p className="text-muted">You will review the live experience, payment details, and voucher option next.</p></>}{error && <p style={{ color: '#be123c', fontWeight: 700, marginTop: 16 }}>{error}</p>}<div className="emotional-creator-actions">{step > 1 && <button className="btn-secondary" onClick={() => setStep(step - 1)}>Back</button>}{step < 4 ? <button className="btn-primary" onClick={advance}>Continue</button> : <button className="btn-primary" disabled={busy} onClick={save}>{busy ? 'Creating…' : `Preview & payment · ₹${template.price}`}</button>}</div></section></div></main>;
}
