export const templates = [
  {
    id: 'sorry',
    title: 'Interactive Romantic Apology',
    icon: '🥺',
    description: 'A 5-step interactive journey: cuteness meter, tap-to-reveal promise cards, memory swiper, and typewriter apology note.',
    time: '≈ 3 min',
    bestFor: ['Apologies', 'Romantic Gestures', 'Making Up'],
    price: 149,
    recommended: true,
  },
  {
    id: 'birthday-surprise',
    title: 'Birthday Surprise',
    icon: '🎂',
    description: 'Red curtain opens, cake appears, fairy helps them blow the candles — pure birthday magic.',
    time: '≈ 2 min',
    bestFor: ['Birthdays', 'Milestone Years', 'Midnight Reveals'],
    price: 149,
    recommended: false,
  },
  {
    id: 'love-letter',
    title: 'Love Letter',
    icon: '💌',
    description: 'A clean, handwritten-style letter — four vibes — for anniversaries, apologies, just-because.',
    time: '≈ 3 min',
    bestFor: ['Anniversary', 'Apology', 'Quiet Moments'],
    price: 149,
    recommended: false,
  },
  {
    id: 'letter-for-mom',
    title: 'A Letter for Mom',
    icon: '💐',
    description: "Warm, handwritten-style Mother's Day letter with a favourite memory and one thing you never told her.",
    time: '≈ 3 min',
    bestFor: ["Mother's Day", 'For Mom', 'Long-Distance Kids'],
    price: 149,
    recommended: false,
  },
  {
    id: 'be-my-valentine',
    title: 'Will You Be My Valentine?',
    icon: '💕',
    description: 'A playful page where the "NO" button runs away — pure smiles guaranteed.',
    time: '≈ 2 min',
    bestFor: ["Valentine's Day", 'Proposals', 'Crushes'],
    price: 149,
    recommended: false,
  },
  {
    id: 'wedding-invitation',
    title: 'Wedding Invitation',
    icon: '💒',
    description: 'Royal red digital save-the-date with live countdown, venue map, and RSVP tracking.',
    time: '≈ 4 min',
    bestFor: ['Indian Weddings', 'Save-The-Date', 'Destination Weddings'],
    price: 149,
    recommended: false,
  },
  {
    id: 'surprise-reveal-box',
    title: 'Surprise Reveal Box',
    icon: '🎁',
    description: 'Tap a wrapped gift box, ribbons untie, lid lifts, confetti bursts, surprises unfold one by one. The most theatrical gift in the lineup.',
    time: '≈ 8 min',
    bestFor: ['Proposals', 'Reveal Moments', 'Big-Day Surprises'],
    price: 149,
    recommended: false,
  },
  {
    id: 'a-rose-for-someone-special',
    title: 'A Rose for Someone Special',
    icon: '🌹',
    description: 'A cinematic rose that blooms on their screen — petals, candlelight, and your words at the heart of it.',
    time: '≈ 4 min',
    bestFor: ['Love Confessions', 'Apologies', 'Just-Because Romance'],
    price: 149,
    recommended: false,
  },
];
