export const templates = [
  {
    id: 'sorry',
    title: 'Interactive Romantic Apology',
    icon: '🥺',
    description: 'A 5-step apology journey: tone selector, heart cuteness meter, promise cards, photo memory reel, and self-typing typewriter note.',
    time: '≈ 3 min',
    bestFor: ['Apologies', 'Romantic Gestures', 'Making Up'],
    price: 149,
    recommended: true,
  },
  {
    id: 'birthday-surprise',
    title: 'Birthday Surprise',
    icon: '🎂',
    description: 'Bollywood red curtain rise, candle-blowing cake with confetti shower, party theme picker, and custom birthday banner.',
    time: '≈ 2 min',
    bestFor: ['Birthdays', 'Milestone Years', 'Midnight Reveals'],
    price: 149,
    recommended: false,
  },
  {
    id: 'love-letter',
    title: 'Love Letter',
    icon: '💌',
    description: '4 stationery designs, wax seal unsealing tap, pen-on-paper typewriter animation, drifting rose petals & glowing lanterns.',
    time: '≈ 3 min',
    bestFor: ['Anniversary', 'Apology', 'Quiet Moments'],
    price: 149,
    recommended: false,
  },
  {
    id: 'letter-for-mom',
    title: 'A Letter for Mom',
    icon: '💐',
    description: 'Cozy pastel tribute featuring shared childhood memories, heartfelt gratitude, and a secret note with blooming flower unfurl.',
    time: '≈ 3 min',
    bestFor: ["Mother's Day", 'For Mom', 'Long-Distance Kids'],
    price: 149,
    recommended: false,
  },
  {
    id: 'be-my-valentine',
    title: 'Will You Be My Valentine?',
    icon: '💕',
    description: 'A playful proposal card where the "NO" button comically dodges away, unlocking a heart explosion on "YES".',
    time: '≈ 2 min',
    bestFor: ["Valentine's Day", 'Proposals', 'Crushes'],
    price: 149,
    recommended: false,
  },
  {
    id: 'wedding-invitation',
    title: 'Wedding Invitation',
    icon: '💒',
    description: 'Regal red & gold save-the-date with live countdown clock, Mehndi/Sangeet/Vivah timeline, venue map link, and instant RSVP form.',
    time: '≈ 4 min',
    bestFor: ['Indian Weddings', 'Save-The-Date', 'Destination Weddings'],
    price: 149,
    recommended: false,
  },
  {
    id: 'surprise-reveal-box',
    title: 'Surprise Reveal Box',
    icon: '🎁',
    description: 'Interactive 3D gift box with ribbon untie, lid pop, confetti burst, and multi-layer sequential surprise reveals.',
    time: '≈ 4 min',
    bestFor: ['Proposals', 'Reveal Moments', 'Big-Day Surprises'],
    price: 149,
    recommended: false,
  },
  {
    id: 'a-rose-for-someone-special',
    title: 'A Rose for Someone Special',
    icon: '🌹',
    description: 'A cinematic virtual rose blooming in candlelight with multi-petal animation and your words at the heart of the bloom.',
    time: '≈ 4 min',
    bestFor: ['Love Confessions', 'Apologies', 'Just-Because Romance'],
    price: 149,
    recommended: false,
  },
];

