// Clean 4-template catalog — no legacy/emotional split
export const templates = [
  {
    id: 'proposal',
    title: 'The Perfect Proposal',
    icon: '💕',
    emoji: '💕',
    accentColor: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.3)',
    gradient: 'linear-gradient(135deg, #f43f5e 0%, #be123c 100%)',
    description: 'A heartfelt yes/no confession where the NO button playfully dodges away — forcing a YES! Sealed with a love letter and memory photos.',
    time: '≈ 3 min',
    price: 219,
    basePrice: 499,
    recommended: true,
    bestFor: ['Proposals', "Valentine's Day", 'Confessions', 'Romantic'],
    defaultAudio: 'romantic-piano',
    photoRequirement: { recommended: 3, min: 0, max: 3, tip: 'Upload up to 3 personal photos.' },
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'who_are_they', label: 'Who Are They', icon: '💞' },
      { id: 'quotation', label: 'For Recipient', icon: '💬' },
      { id: 'photos', label: 'Make It Personal', icon: '📸' },
      { id: 'letter', label: 'Letter', icon: '✉️' },
    ],
  },
  {
    id: 'birthday',
    title: 'Virtual Birthday Bash',
    icon: '🎂',
    emoji: '🎂',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.3)',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #b45309 100%)',
    description: 'A cinematic birthday journey — balloon pop reveals, a growing heart-leaf tree, cake cutting, memory gallery, and a love letter.',
    time: '≈ 4 min',
    price: 219,
    basePrice: 499,
    recommended: true,
    bestFor: ['Birthdays', 'Milestone Years', 'Midnight Reveals'],
    defaultAudio: 'birthday-joy',
    photoRequirement: { recommended: 3, min: 1, max: 5, tip: 'Upload 1-5 memory photos.' },
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'cake', label: 'Select the Cake', icon: '🎂' },
      { id: 'balloons', label: 'Balloon Messages', icon: '🎈' },
      { id: 'memories', label: 'The Memories', icon: '📸' },
      { id: 'letter', label: 'Birthday Letter', icon: '✉️' },
    ],
  },
  {
    id: 'anniversary',
    title: 'Anniversary Special',
    icon: '🥂',
    emoji: '🥂',
    accentColor: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 0.3)',
    gradient: 'linear-gradient(135deg, #fbbf24 0%, #92400e 100%)',
    description: 'A live countdown of your time together, a journey timeline, champagne toast, love meter, and a sealed letter with your deepest reasons.',
    time: '≈ 4 min',
    price: 219,
    basePrice: 499,
    recommended: true,
    bestFor: ['Anniversaries', 'Romantic Milestones', 'Couples'],
    defaultAudio: 'romantic-piano',
    photoRequirement: { recommended: 3, min: 0, max: 5, tip: 'Upload up to 5 memory photos.' },
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'special_dates', label: 'Special Dates', icon: '📅' },
      { id: 'journey', label: 'Journey Together', icon: '🗺️' },
      { id: 'memories', label: 'Picture Memories', icon: '📸' },
      { id: 'reasons', label: 'Why You Love Them', icon: '❤️' },
      { id: 'letter', label: 'A Love Letter', icon: '✉️' },
    ],
  },
  {
    id: 'emotional-apology',
    title: "I'm Sorry",
    icon: '🥺',
    emoji: '🥺',
    accentColor: '#94a3b8',
    glowColor: 'rgba(148, 163, 184, 0.3)',
    gradient: 'linear-gradient(135deg, #94a3b8 0%, #475569 100%)',
    description: 'A sincere apology with a handwritten letter, a forgiving YES/NO game, and memory photos — giving them the space to truly feel your words.',
    time: '≈ 3 min',
    price: 219,
    basePrice: 499,
    recommended: true,
    bestFor: ['Apologies', 'Reconciliation', 'Heartfelt', 'Partner', 'Friend', 'Family'],
    defaultAudio: 'sincere-acoustic',
    photoRequirement: { recommended: 2, min: 0, max: 3, tip: 'Add up to 3 personal photos.' },
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'what_happened', label: 'What Happened', icon: '💔' },
      { id: 'letter', label: 'Write From Your Heart', icon: '✍️' },
      { id: 'memories', label: 'Add Memories', icon: '📸' },
    ],
  },
];
